### ISSUE TITLE
Doesn't work, even in preview field

### ISSUE THREAD

**Issue by ozra** [braver/fonts#12]
Lovely idea for a plugin - but not working at all for me. Atom 0.200.0 on Ubuntu 14.04 64b.

**Comment by braver** [comment]
There seems to have been changes in package activation that aren't handled well. This has been unstable in Atom's core for months, not much I can do at this point. Although I do expect to be able to perfect this as soon as Atom hits 1.0 somewhere next month.

However, it isn't broken per se, just the activation after installation that doesn't work well.

If you reload Atom after activating the fonts package, it should work and update the preview.

**Comment by ozra** [comment]
Ok, I'll try. B/c if I deactivate and reactivate, it changes font, but only the same one.. I'll check.

**Comment by ozra** [comment]
Now the settings are even missing, after restarting(!)

**Comment by ozra** [comment]
deact/react of fonts now switches between my confed font (deactivated), and a non-mono-font (activated). And fonts-settings are missing - other packages settings show as usual.
Weird. Do I need to run in API 1.0 mode?

**Comment by braver** [comment]
Glad it finally works out :+1:
