### ISSUE TITLE
Updated Hack version released

### ISSUE THREAD

**Issue by chrissimpkins** [braver/fonts#15]
Thank you very much for including Hack in your font package for Atom.  I wanted to let you know that a new major version has been released with a large number of improvements and a significant expansion of the glyph set that provides broad multilingual support.  The best binaries to use are the ttf files in this directory: 

https://github.com/chrissimpkins/Hack/tree/master/build/ttf

Thanks!

**Comment by gabriel** [comment]
https://github.com/braver/fonts/pull/16

**Comment by chrissimpkins** [comment]
Thank you!

**Comment by gabriel** [comment]
@chrissimpkins Do you think there is a significant difference between the ttf and the woff?

**Comment by chrissimpkins** [comment]
Either should be fine if you are using the extended woff.  The latin woff is a smaller character set that is intended for the web.

**Comment by gabriel** [comment]
yeah i used the regular (non-latin)... I renamed them to match the previous file names so I didn't have to change any css

**Comment by chrissimpkins** [comment]
no problem at all.  that is fine.  thank you very much for adding them.  i really appreciate it!

**Comment by braver** [comment]
Woff is mostly aimed at providing a way to not expose installable fonts to the public. They might be more compressed or otherwise optimised, but they offer no real benefit in this case.

**Comment by chrissimpkins** [comment]
@braver The only potential issue that I see is the consistency of the hinting.  Let me know if that appears to be an issue.

**Comment by braver** [comment]
This has been fixed in #16 and d769be45e3ac71f7c7bb299fcc01431de24d4640 again updates Hack (now using the woff2 files for improved compression)

**Comment by chrissimpkins** [comment]
Thank you!
