### ISSUE TITLE
requesting input: solve incorrect measurements

### ISSUE THREAD

**Issue by braver** [braver/fonts#2]
Atom runs measurements to determine how large the characters of the selected font are. This determines caret placement among other things. 

@font-face fonts are only loaded by Chromium when the editor is fully loaded and painted. This is too late for the measurements, which makes Atom run the measurements with a default font (Times New Roman).

As soon as a font has been loaded once, the next time the measurements will be correct. Therefore, this problem only occurs on the file that is open when Atom is opened (or reloaded). Each subsequent file, newly opened or by switching tabs, will be fine.

Related issues tracked elsewhere:
- https://github.com/atom/atom/issues/4200
- https://github.com/atom/atom/issues/3201

I have investigated solving this problem with the [Google/Typekit Web Font Loader](https://github.com/typekit/webfontloader). However, this does not work properly within Atom. Atom is a different environment, and the problem it tries to solve is also different.

The ideal solution would be to force the measurements to be run again. However...

I don't know if the measurements can be initiated directly. A quick and dirty method would be by calling `atom.workspace.increaseFontSize()` and `atom.workspace.decreaseFontSize()`, which immediately solves the problem.

I don't know if there is an event that could trigger this. window.onload happens too early and I don't know of any events in Atom that will help solve this problem. 

So, I'm lacking some knowledge and programming skills to put the finishing touch on this package. **Any help is welcome!**

**Comment by braver** [comment]
I'm currently solving this by:

* Appending an element to the workspaceView to force chromium to load all styles of a font immediately when the selected font changes
* Increasing and decreasing font sizes a bunch of times every time the font changes or Atom opens or reloads

Especially that last step is messy, but all other events that happen when a config changes or Atom loads are too early. Chromium postpones loading the font files and doesn't send any events when it does this.

**Comment by leofle** [comment]
workspaceView is deprecated.
If you do need the view, use atom.views.getView(atom.workspace),
which returns an HTMLElement.

**Comment by braver** [comment]
While it is kinda messy, the current implementation seems to work fine and without side effects. Best we can do with the tech available.
