### ISSUE TITLE
import chrissimpkins/codeface instead

### ISSUE THREAD

**Issue by tomByrer** [braver/fonts#20]
I think Chris's list is more complete & has more action/updates.  Would be easier just to link his folder in git or what ever auto-importing, don't you think?  Be lazy; let him do all the updates (some fonts have monthly releases), & you can shoot a PR to him for the few updates he's missing.
https://github.com/chrissimpkins/codeface/tree/master/fonts

**Comment by braver** [comment]
I hadn't heard of this, and he apparently never heard of my projects because that could've saved him a lot of work (he started only a few months ago). Thanks for pointing me to this, I'll definitely reach out to him about collaborating!

Kind regards,
Koen

**Comment by braver** [comment]
We are collaborating and sharing info. I don't think we'll do a real link of the source code through a subtree or anything like that though.
