### ISSUE TITLE
Does not work with Atom 1.7

### ISSUE THREAD

**Issue by nikolay** [braver/fonts#23]

**Comment by braver** [comment]
Have you tried reloading atom?

**Comment by nikolay** [comment]
@braver Yes, of course.

**Comment by nbolt** [comment]
working on 1.7 over here.

**Comment by anttimo** [comment]
When I go to packages and search for 'fonts' package Atom doesn't find it. I have Atom 1.7.3 on OSX. Is this same issue you are having @nikolay or can you actually install the package and it doesn't work?

**Comment by nbolt** [comment]
I am on 1.7.3 on OSX and see the fonts package fine.

**Comment by braver** [comment]
@anttimo, you sure you're not confusing the packages and install menu items? I always try to install through the packages menu myself...

**Comment by braver** [comment]
Also, by lack of any signs of stuff really not working, I'm closing this issue.

**Comment by anttimo** [comment]
Yeah, that was it. Thanks :) I was kinda suspecting something like that but still missed the separate install menu item.

**Comment by nikolay** [comment]
@braver There's no font drop down as depicted. Basically, once I install this plugin, nothing happens.

**Comment by braver** [comment]
Could you upload a screenshot of the screen where the drop down menu is missing?

**Comment by nikolay** [comment]
@braver The package has no settings: http://bit.ly/1WGOR5W

**Comment by nikolay** [comment]
@braver Weird! After reinstalling and restarting Atom, I see it now! I apologize, maybe it's an Atom bug instead.

**Comment by braver** [comment]
Well, package, settings, and stylesheet initialization and de-initialization are a bit complicated and last time I checked kinda quirky. This is the best I could get it for this package, but I bet it could be better.
