### ISSUE TITLE
More fonts to add

### ISSUE THREAD

**Issue by nikolay** [braver/fonts#26]
https://news.ycombinator.com/item?id=11715532

**Comment by braver** [comment]
I covered most of those as far as licenses allow. I do kinda require it to be more that just something someone found on a free fonts website and there is a bunch of those in that list (e.g. the Cruft font) or another repackaged Bitstream Vera derivative without any distinguishing characteristics (e.g. Panic). By going through te list I did find Triskweline though, I haven't heard of that before.

**Comment by nikolay** [comment]
@braver Hopefully, people would keep adding to the list - I wasn't clear and I apologize, but I didn't mean this to be a single shot, but, maybe, a subscription to monitor if meaningful new fonts are added there.

**Comment by braver** [comment]
Ugh, Triskweline doesn't even work. Anyway, thanks for the link and if you find anything new, please let me know|!

**Comment by nikolay** [comment]
@braver Some more here: https://fontlibrary.org/en/search?category=monospaced

**Comment by braver** [comment]
Thanks, I think I got most of those already. There are a lot of display fonts in there though.
