### ISSUE TITLE
Allow input secondary font family name

### ISSUE THREAD

**Issue by WindieChai** [braver/fonts#30]
If user can specify secondary font family, then the editor can render CJK character more beautiful, since most programming fonts don't include CJK character.

**Comment by braver** [comment]
How about if I'd use the font-family specified in the regular preferences pane as the secondary font?

**Comment by barrar** [comment]
Monospace CJK can be found here, does this help?
https://github.com/googlei18n/noto-cjk#2c4e9f326ad39d6d8152e3916ffd4205-3ac7b283f6cbb7b76ea7e4a1479a1e26a3ab62f5

**Comment by barrar** [comment]
For example this font has english characters and japanese in one font, and it's monospace
https://github.com/googlei18n/noto-cjk/blob/master/NotoSansMonoCJKjp-Regular.otf

**Comment by braver** [comment]
@WindieChai, @barrar it took me quite a while to figure out how to implement this, but I think I've got something up and running with the 3.0.0 release just now. It will allow you to enter a font family string with additional fallback fonts.

**Comment by barrar** [comment]
Wow nice job! Thank you!
