### ISSUE TITLE
Fantasque-sans-mono(and some others) renders incorrectly on Windows(10)

### ISSUE THREAD

**Issue by tsuggate** [braver/fonts#32]
I've seen this same issue on both windows machines I've tried:

![badfontrendering](https://cloud.githubusercontent.com/assets/19199926/16827018/962177fa-49d6-11e6-853b-1d5984ac2815.PNG)

**Comment by braver** [comment]
I think this is mostly due to hinting? I see they have a new version out, I'll look into updating the font files. Any specific other fonts you have this problem with?

**Comment by braver** [comment]
Fantasque should be improved in https://github.com/braver/fonts/commit/35ae61be90f4955d9e87130e8e7384a80a6d4dea

**Comment by tsuggate** [comment]
Thanks for responding so quickly. Other fonts that are rendering strange for me are:  
 - Code New Roman (at font size 15)
 - Mononoki - brackets look like they don't line up right

**Comment by braver** [comment]
Mononoki has a new build out, I updated them in https://github.com/braver/fonts/commit/eec57cdb99305c204bbc463af351c42bb533a420. Hopefully that improves stuff for you! Code New Roman is already at the latest, so nothing much to do there.
