### ISSUE TITLE
Updates for FiraCode?

### ISSUE THREAD

**Issue by blaqbern** [braver/fonts#34]
I opened an issue on FiraCode about GIT conflict markers rendering awkwardly, and @tonsky pointed out that there was a fix for that in version  1.200. tonsky/FiraCode#234

Any plans to keep fonts like FiraCode, Monoid and Hasklig up to date?

Thanks for all the monospaced goodness

**Comment by braver** [comment]
Yeah, there are "plans", but no automation so in general I try to do updates a few times a year. It's not complicated though, so pull requests are definitely welcome!

**Comment by liuchangxing** [comment]
Why all fonts are the same, it does not change
![qq 20160924114731](https://cloud.githubusercontent.com/assets/22342099/18805896/ed49bb88-824c-11e6-91fd-6c8a11c7ac27.png)

**Comment by liuchangxing** [comment]
I do not like this……Please help me

**Comment by braver** [comment]
@liuchangxing try restarting atom.
