### ISSUE TITLE
[Suggestion]: Font Preview Placement

### ISSUE THREAD

**Issue by 3DEsprit** [braver/fonts#36]
Would it be a lot of trouble to put the font preview above the font family drop-down, so that it's always visible?

**Comment by braver** [comment]
What do you mean with "always visible"?

**Comment by 3DEsprit** [comment]
Well, even though it may not update until the font is selected, the drop-down covers the preview. It just feels very obstructive.  

Maybe if there is ever a time when it could change when hovering on an option from the drop-down, it would be even more helpful. That is assuming it doesn't already.

**Comment by braver** [comment]
I think that might be os specific as well. But it's a fair point. Config is sorted alphabetically so, it should be pretty easy to switch them around.

**Comment by 3DEsprit** [comment]
Indeed. With OSX it wouldn't make too much of a difference depending on where you are in the list, but Windows and Linux do drop down from the position of the menu element.

**Comment by braver** [comment]
Unless the select box is close to the bottom of the screen. If I recall correctly, the drop down menu on Windows will actually "drop up" if it doesn't fit. The logical order is the order it's currently in. The good solution would be to have them side by side. I don't really feel like going for a half baked option where it works most of the time but is also a bit weird.
