### ISSUE TITLE
Can you move the Preview *above* the select

### ISSUE THREAD

**Issue by crayfishuk** [braver/fonts#38]
The select box obscures the Preview box. It would be better to have it above the Select, because you can then cycle through the fonts using the up/down key seeing the previews change...

It's a bit of a PITA at the moment... :-)

**Comment by braver** [comment]
Duplicate of #36

**Comment by braver** [comment]
I know it's a bit of a pain, but putting it above the select doesn't solve it in all cases either.

**Comment by crayfishuk** [comment]
Doh! - looked through the Issues twice before raising this one. More coffee needed...

**Comment by braver** [comment]
> More coffee needed...

Always!
