### ISSUE TITLE
Fonts not installing

### ISSUE THREAD

**Issue by nithishv** [braver/fonts#49]
Tried to install Fonts package with Atom editor.

Installation did not finish after over 20 Minutes. Atom kept showing the following error many times.
`Cannot read property 'fnType'`
before finishing installation.

My Internet was working fine, as I was able to install other packages.

**Comment by braver** [comment]
@nithishv Could be just a hiccup or something, it's a pretty big package with all the fonts. Could you try to install 1.8.0 and if it fails re-open?
