### ISSUE TITLE
install

### ISSUE THREAD

**Issue by ShadySinister** [braver/fonts#56]
packages won't install

**Comment by braver** [comment]
As you can imagine I need a bit more information than that.

**Comment by frob** [comment]
I don't even see it in the list of packages.

**Comment by braver** [comment]
It's right there for me:

<img width="767" alt="screen shot 2017-05-14 at 18 00 14" src="https://cloud.githubusercontent.com/assets/2543659/26035579/3e3a35ca-38cf-11e7-8a4b-bec0e5abbcb8.png">

**Comment by frob** [comment]
Yup, must have been a network error or solar flair. I have it now too. Thanks.
