### ISSUE TITLE
Please add "Terminus TTF" font

### ISSUE THREAD

**Issue by MrUlmo** [braver/fonts#57]
HI.

I would like to know if you would add the "Terminus TTF" font?

You can find it [Here](https://files.ax86.net/terminus-ttf)

Thanks in advance

/MrUlmo

**Comment by braver** [comment]
Thanks for the link! Can't remember what was wrong with previous versions, but the latest seems to work just fine. It's available [in the test driver](http://app.programmingfonts.org/#terminus) and in version 2.1.0 of the Fonts package.
