### ISSUE TITLE
atom-workspace selector not working

### ISSUE THREAD

**Issue by barrar** [braver/fonts#59]
I had to use this:
```
atom-text-editor {
    font-family: "Noto Mono";
}
```

This did not work:
```
atom-workspace {
    font-family: "Noto Mono";
}
```

**Comment by braver** [comment]
works just fine here, but styling `atom-workspace` doesn't style the code editing area (which is by design)

**Comment by barrar** [comment]
I missed that point, thanks for clarifying. It would be nice if the monospace font package included instructions on how to change the font of the code.

**Comment by barrar** [comment]
I never installed the package, I just Googled for "how to change atom font" and thought that "atom-workspace" was the proper selector for what I wanted. Side note: Noto Mono is not included in your package. It's similar to Consolas, and I think it looks great!

**Comment by braver** [comment]
Noto is just Droid Sans rebranded, and Droid Sans is available in the package.
