### ISSUE TITLE
Can't change font

### ISSUE THREAD

**Issue by yoanndw** [braver/fonts#61]
When I select a font in the menu, the preview (and the font) don't change

Can you help me please ?

**Comment by braver** [comment]
Sure, but I need some more info:

- any specific font you're selecting?
- does it happen with all fonts?
- which packages do you have installed?
- can you try with just the fonts package installed?

It's pretty easy for this to conflict with another package. But I need to know where to look.

**Comment by yoanndw** [comment]
My packages are:
- lua language
- love2d framework support
- atom-minimap

For the fonts, this issue appears for all of them

Le jeu. 15 juin 2017 22:04, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by braver** [comment]
@yoanndw I can't reproduce the problem. 2 questions:

- which package exactly is the "love2d framework support"
- do you have anything custom in your stylesheet?

**Comment by yoanndw** [comment]
Love2d is a framework for gamedev, and with the love2d framework support, I
can use it un Atom

Le ven. 16 juin 2017 12:24, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by yoanndw** [comment]
In Atom*

**Comment by braver** [comment]
Yes, I understand but can't find the package on atom.io/packages.

**Comment by yoanndw** [comment]
It doesn't called "love2d framework support"
Try with love2d or just love

Le ven. 16 juin 2017 12:28, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by yoanndw** [comment]
I found it :
https://atom.io/packages/love-atom

**Comment by braver** [comment]
Thanks. Still no repro though.

Do you have anything custom in your stylesheet?

**Comment by yoanndw** [comment]
I have a ui theme called material ui (Google's material design)
And à syntax theme pico8 syntax

Le ven. 16 juin 2017 14:07, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by braver** [comment]
I just published 3.0.2. Could you try if that fixes it for you? If not, please try to add the following to your stylesheet:

```
fonts-fixer,
atom-text-editor {
  font-family: var(--fonts-package-editorfont) !important;
}
```

**Comment by yoanndw** [comment]
Where do I copy the code that you gave ?

Le ven. 16 juin 2017 14:20, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by braver** [comment]
http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks

**Comment by yoanndw** [comment]
In styles.less file ?

Le ven. 16 juin 2017 14:44, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by braver** [comment]
yes, if you follow those instructions atom opens a styles.less file you can edit and save.

**Comment by yoanndw** [comment]
It works !
Thanks you very much !

Le ven. 16 juin 2017 14:51, Koen Lageveen <notifications@github.com> a
écrit :

**Comment by braver** [comment]
Well, that's a bit weird but at least there's a workaround :)
