### ISSUE TITLE
Some unicode characters aren't included in all fonts

### ISSUE THREAD

**Issue by fkrz** [braver/fonts#65]
Example : accented letters in M+ fonts

![2017-11-13-133839_1366x768_scrot](https://user-images.githubusercontent.com/26671073/32726327-e52f51ec-c878-11e7-9fa7-84da68beaf45.png)

Package version 3.0.3 under Linux, if it's relevant

**Comment by braver** [comment]
Sure, not all fonts cover all of unicode. Or rather, no font has full coverage. Nothin much I can do about that, that's why there is a "secondary font" setting that'll provide the glyphs that you're missing.

**Comment by fkrz** [comment]
Sure, but doesn't M+ (for example) cover all of it ? I don't seem to have any problem with the same font in urxvt : 

![2017-11-13-135309_1366x768_scrot](https://user-images.githubusercontent.com/26671073/32726693-216e076a-c87a-11e7-9f1b-712b06acdbf5.png)

**Comment by braver** [comment]
I'm using their woff (webfont) release, which limits Latin coverage to Basic Latin. All the glyphs (Kanji etc) make M+ too massive to include completely. Some other fonts are also huge (i.e. tens of megabytes) and not included with their complete set. If you like using M+ I recommend just installing it on your machine.
