### ISSUE TITLE
Add Font: Meslo LG L Regular for Powerline

### ISSUE THREAD

**Issue by lamar-frankie** [braver/fonts#67]
Please add: Meslo LG L Regular for Powerline

This is a common font among zshell users. 

https://github.com/powerline/fonts

**Comment by braver** [comment]
Does Atom have a powerline?

**Comment by lamar-frankie** [comment]
The terminal plugins do. Currently, it doesn't render the special characters.

**Comment by lamar-frankie** [comment]
terminal plugin

<img width="595" alt="screen shot 2017-12-07 at 2 58 44 pm" src="https://user-images.githubusercontent.com/6373522/33736112-704ceef8-db5f-11e7-835b-6c722184fd4c.png">

**Comment by lamar-frankie** [comment]
How it should look (iterm)

<img width="486" alt="screen shot 2017-12-07 at 2 59 37 pm" src="https://user-images.githubusercontent.com/6373522/33736131-8077ce88-db5f-11e7-9d62-2d1d2683f437.png">

**Comment by braver** [comment]
ok, super nice! would definitely accept a PR that adds some or most of the power line fonts from that repo.

**Comment by lamar-frankie** [comment]
Sure thing! I'll work on that this weekend. Thanks.

**Comment by braver** [comment]
Well sorry about that, I didn't expect the size to almost double with those powerline fonts. As such it's "won't fix" for this package, but publishing a new package with just these fonts should be easy enough. I don't use Atom enough to put in the effort and take on the maintenance myself though.

**Comment by lamar-frankie** [comment]
How about I just add 2 or 3 of the fonts instead of all of them?

**Comment by braver** [comment]
Well that would be kinda random...

**Comment by lamar-frankie** [comment]
And self serving. I'd just add the power line fonts that I use, Hack and
Meslo. I use atom everyday. It's sucks that some of the characters don't
render.

**Comment by braver** [comment]
Can’t you just install those fonts on your system and use them that way?

**Comment by lamar-frankie** [comment]
Atom doesn't recognize custom system fonts. It's recognizes this font
package and the default system fonts.

On Dec 17, 2017 10:29 AM, "Koen Lageveen" <notifications@github.com> wrote:

Can’t you just install those fonts on your system and use them that way?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/braver/fonts/issues/67#issuecomment-352263670>, or mute
the thread

**Comment by braver** [comment]
> Atom doesn't recognize custom system fonts

Are you sure? That hasn't been my experience and I don't understand why that would be the case.
