### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by giannwilk** [braver/fonts#7]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/amugxw1/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
triggerMeasurements (/Users/amugxw1/.atom/packages/fonts/lib/runner.coffee:8:13)
```

**Comment by braver** [comment]
This has been fixed in https://github.com/braver/fonts/commit/9a0b9cdeba17424933912751a400d388e71b1b35
