### ISSUE TITLE
no "Settings" button to change fonts

### ISSUE THREAD

**Issue by stockbrot** [braver/fonts#70]

**Comment by mrsimb** [comment]
Same thing
![2018-01-24 11-49-01](https://user-images.githubusercontent.com/7318420/35322811-9fe2d43a-00fc-11e8-9044-7bc51992a3ea.png)

**Comment by lierdakil** [comment]
Pretty sure this was a bug in a couple Atom versions. Unable to reproduce in v1.27.2:
![image](https://user-images.githubusercontent.com/7275622/41448359-d97c4b42-7062-11e8-8460-c96236fc55f0.png)
Please open new issues if this still happens on current Atom versions.
