### ISSUE TITLE
Even if font selected font does not change

### ISSUE THREAD

**Issue by matthiaschung** [braver/fonts#71]
I am working on a Mac (Atom 1.23.3). I installed the fonts 3.0.3, however even when selecting a new font family in the setting nothing is updated not even the preview window shows the selected font. Any ideas? Thank you.

**Comment by nobleach** [comment]
You will probably see it flash when you first launch Atom, and then revert to whatever is in your settings. I'm seeing the same behavior. I did see it work just fine with a previous version of Atom.

**Comment by braver** [comment]
I haven’t had time to really maintain this, so perhaps something about the API changed that broke this. Someone wants to help out, I’d be very grateful.

**Comment by nobleach** [comment]
Actually, I'd encourage the original reporter to check out Electron Dev Tools `COMMAND+ALT+i` or `CONTROL+ALT+i` (depending on your OS). Then inspect some text in the editor. It's entirely possible that there is some other package overriding this one. I dug a bit deeper into this and found that I had the hasklig package applying another font as the default. Getting a list of the computed styles:

<img width="668" alt="screenshot 2018-02-18 14 18 36" src="https://user-images.githubusercontent.com/217134/36357133-b4c39e7a-14b6-11e8-8f09-1d2d6fab6eeb.png">
One can see where that rule is coming from. For me, I saw an overriding `@font-face` attribute that took more precedence.

Hope that helps.

**Comment by matthiaschung** [comment]
I de-installed the fonts package and re-installed. Now everything works perfectly for me.
