### ISSUE TITLE
Add open-fonts collection (together with fallback fonts) for Markdown Preview Plus

### ISSUE THREAD

**Issue by kiwi0fruit** [braver/fonts#82]
[open-fonts](https://github.com/kiwi0fruit/open-fonts) (all with Unicode fallback chains of other fonts) that can be used in Markdown Preview Plus:

* Noto Sans LGC (sans)
* Lato (sans)
* Source Sans Pro (sans)
* Libertinus Serif (serif)
* STIX Two Text (serif)
* Open Mono (Roboto Mono with monospacified italic) (mono)
* [Fallback fonts for Consolas](https://github.com/kiwi0fruit/sugartex#atom-editor-with-full-unicode-support)

I can add them to the separate package. But it worth considering adding them here.

**Comment by lierdakil** [comment]
Why is MPP relevant?

**Comment by kiwi0fruit** [comment]
That's the only Atom package I know that uses non-monospace fonts. May be
there are more but I don't know.

**Comment by kiwi0fruit** [comment]
We are talking about including non-monospace fonts.

сб, 17 нояб. 2018 г., 10:22 Nikolay Yakimov notifications@github.com:

**Comment by kiwi0fruit** [comment]
As for me it would be more convenient to go with a separate package. And non-monospace fonts are not quite fit here.
