### ISSUE TITLE
Newest additions from Programming Fonts

### ISSUE THREAD

**Issue by vekuda** [braver/fonts#84]
I just visited [Programming Fonts' Test Drive](https://app.programmingfonts.org/) area and I have found that a bunch of monospace coding typefaces are missing from the 'fonts' atom package:

- [Agave](https://github.com/agarick/agave)
- [APL2741](http://apl385.com/fonts/index.htm)
- [APL385](http://apl385.com/fonts/index.htm)
- [B612](https://github.com/polarsys/b612)
- [Bedstead](https://bjh21.me.uk/bedstead/)
- [BPmono](https://www.fontsquirrel.com/fonts/BPmono)
- [Bront DejaVu Sans Mono](https://github.com/chrismwendt/bront)
- [Bront Ubuntu Mono](https://github.com/chrismwendt/bront)
- [DaddyTimeMono](https://github.com/BourgeoisBear/DaddyTimeMono)
- [iA Writer Mono](https://github.com/iaolo/iA-Fonts)
- [Input](http://input.fontbureau.com/)
- [Mensch](https://robey.lag.net/2010/06/21/mensch-font.html)
- [Nano Gothic Coding](https://github.com/naver/nanumfont)
- [OpenDyslexic Mono](https://www.opendyslexic.org/) (this one undoubtedly very important)
- [Press Start 2P](https://github.com/codeman38/PressStart2P)

I played with all of these these, and I do believe that most of them are extremely nice or useful: would you please consider importing them in your excellent 'fonts' package?

**Comment by lierdakil** [comment]
There are a few licensing problems with some of these fonts:

- Input can't be redistributed under its licence agreement, so that one's out of the question.
- Mensch is on very unclear legal ground itself, since it's derived from Apple's Menlo font, which is not itself distributed under an open licence.
- Can't really verify what licence is Nanum Gothic Coding using, since I don't read Korean. Seems like OFL v1.1, but I'd prefer for someone to verify that.

**Comment by lierdakil** [comment]
That said, pull requests are welcome for the rest of those.

**Comment by vekuda** [comment]
Thank you for writing back 

> See the contributing guide if you want to help out.

I would love to lend a hand, but I don't know the first thing about coding. The first two steps are easy,  but for the rest... I have played with Mac OS and Manjaro terminals a couple of times in my life and I actually I use atom only to write content.

I could even give it a try, but I would need far more detailed instructions and I'd still be afraid that I might cause some trouble.

**Comment by lierdakil** [comment]
> The first two steps are easy

Actually, those two steps are by far the most "manual" and time-consuming. So if you could do that, it'd be a huge help, actually. If you follow the naming convention, the rest can be done semi-automatically on our end.

**Comment by vekuda** [comment]
Excellent, I will start ASAP. 

Granted that Input, Mensch and Nanum Gothic Coding will be left out, and that I will pay attention to the licences of the remaining fonts - please double-check such licences as soon as I compete the task.

**Comment by vekuda** [comment]
OK, I got the folders ready as per contribution guide. However I can't manage to import them to braver/fonts/resources.

Now, I'm not familiar with github at all... so I only did what was suggested by the UI: I copied the repository on my PC via GitHub for Desktop, then I uploaded successfully the files and pulled a request. But from what I can see I have unwillingly created some sort of fork of your project (https://github.com/vekuda/fonts). Of course I will delete it as soon as we accomplish this task.

Could you please help me to import the font directories inside your package? [I put them into this .zip attachment](https://github.com/braver/fonts/files/2971430/new-fonts-licenses.zip)

P.S.
I couldn't add APL2741 and APL385 because they have no explicit license to go with them.

**Comment by lierdakil** [comment]
> I have unwillingly created some sort of fork of your project

That's just how GitHub works, it's fine.

You did most things correctly, but you've made a pull request against your own fork, when you needed to make a PR against this repo instead. No worries, I can do that -- in fact I did in #86.

> APL2741 and APL385 [...] have no explicit license

It's a bit inconvenient, yes. The best we have in terms of licence for those fonts is this:

> All fonts listed on this page [APL2741, APL385 and APL333] are original artwork by Adrian Smith, and are freely placed into the public domain.

Which should be fine actually.

**Comment by vekuda** [comment]
Excellent. 

Can I delete my fork now?

**Comment by lierdakil** [comment]
Sure

**Comment by lierdakil** [comment]
Okay, released as v 3.3.0. Thanks for your help!

**Comment by vekuda** [comment]
Thank you for the very useful work!
