### ISSUE TITLE
Quinze flagged as virus

### ISSUE THREAD

**Issue by plttn** [braver/fonts#9]
https://forums.comodo.com/av-false-positivenegative-detection-reporting/font-file-on-github-detected-as-malware-t110382.0.html

Confirmed this with Avast as well, I had them flagged on my end first, which led me to look for any other mentions of it.

**Comment by braver** [comment]
Well that's odd, they're from a respectable source. I'm not sure what to make of that discussion though, why don't those guys communicate more clearly?

**Comment by braver** [comment]
@plttn the author of Quinze updated the font files and virustotals.com doesn't detect any problems. And update to this package will restore Quinze as an option.
