### ISSUE TITLE
Fire Code v2

### ISSUE THREAD

**Issue by ahallicks** [braver/fonts#93]
Fira Code has a new version!

https://github.com/tonsky/FiraCode/releases/tag/2

Would it be possible to get this added at some point?

Thanks!

**Comment by lierdakil** [comment]
Thanks for the heads-up!

Sure, we could add it. The only question is, do we add it separately, or simply update our existing Fira Code font to v2? @braver, any input on this?

**Comment by braver** [comment]
`2 > 1` so it must be better 😄  I'd say drop the nice new font on everyone and out with the old.

**Comment by lierdakil** [comment]
Released as v3.6.0
